"""empty message

Revision ID: 077120252aa2
Revises: 
Create Date: 2021-03-28 20:17:53.057195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077120252aa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.Integer(), nullable=False),
    sa.Column('alcoholism', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.Integer(), nullable=False),
    sa.Column('sms_received', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('patient')
    # ### end Alembic commands ###
